### ISSUE TITLE
Upgrade to .NET Standard

### ISSUE THREAD

**Issue by bryanvam** [Opturne/WorkingDaysManagement#2]

**Comment by Opturne** [comment]
Done in last commit

**Comment by bryanvam** [comment]
Thanks. I looked at https://github.com/Opturne/WorkingDaysManagement/commit/3fcba629db4aa20bff9ff43f87cbe4c1d88f7cae

Seems like you just upgraded to .Net 4.7.2 and not .Net Standard.

**Comment by bryanvam** [comment]
can nuget also be updated please

**Comment by Opturne** [comment]
https://www.nuget.org/packages/WorkingDaysManagement/2.0.0
